### ISSUE TITLE
Scss to css

### ISSUE THREAD

**Issue by madoar** [daniele-zurico/angular2-library#2]
Does the scss file automatically get processed to an "ordinary" css file with the used build script?

In addition: 
If I want to use less files instead of scss files I only need to change the function: 
```
function copyScss () {
    gulp.src('./src/components/**/*.scss')
        .pipe(gulp.dest('./dist/components')).on('end', inlineResource);
}
```
in gulpfile.js to:
```
function copyLess () {
    gulp.src('./src/components/**/*.less')
        .pipe(gulp.dest('./dist/components')).on('end', inlineResource);
}
```
In addition I only need to change the call from copyScss to copyLess, right?

**Comment by daniele-zurico** [comment]
I didn't tried with sass but it should be exactly the same
